### PR TITLE
Added command for Auto-Grouping

### PR DESCRIPTION
**Pull request by SriPallaviDamuluri**
closes Issue #12 
@chandur626 @HariniBharata @nirajlavani @05sandesh

### CODE REVIEW

**Comment by SriPallaviDamuluri** [comment]
Autogrouping is implemented as part of groups.py cog and tests are part of testbot.py

**Review by 05sandesh — APPROVED** [review]

**Comment by chandur626** [comment]
Does this PR include $auto-assign and $find-group commands that we have discussed previously?

**Comment by SriPallaviDamuluri** [comment]
> Does this PR include $auto-assign and $find-group commands that we have discussed previously?

**Review by chandur626 — APPROVED** [review]

**Review by HariniBharata — APPROVED** [review]
approved

**Comment by SriPallaviDamuluri** [comment]
> > Does this PR include $auto-assign and $find-group commands that we have discussed previously?

@chandur626 , Implementation of $find-group is done part of find-group branch, I have merged that branch into this. Both the branches are up-to-date

**Pull request merged**
