### PR TITLE
Task 8/email attachement on reaction

### PR DESCRIPTION
**Pull request by chandur626**
Email attachment to a user up on white_heavy_mark reaction on discord.

### CODE REVIEW

**Comment by chandur626** [comment]
This PR contains changes related to sending an email to the user when reacting to a message with an attachment with a white-heavy mark.
The following things have been taken care of.
1. Email Utility is made generic so that it can be used to send a plain body or attachments.
2. Defined test case in test_bot.py

**Comment by SriPallaviDamuluri** [comment]
@chandur626 ,  are username and password defined static, or can be dynamic?

**Comment by chandur626** [comment]
They are not statically defined rather they are taken from the environment variables.

**Review by HariniBharata — APPROVED** [review]
approved

**Review by SriPallaviDamuluri — APPROVED** [review]

**Review by 05sandesh — APPROVED** [review]

**Pull request merged**
