### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nirajlavani**
- contributors page
- fixed links to userRanking and dataviz commands
- changed gif location to be below description

### CODE REVIEW

**Comment by chandur626** [comment]
@nirajlavani are the readme links getting redirected properly?

**Comment by nirajlavani** [comment]
Yeah the command links in readme will redirect to the dedicated page for each command

**Comment by chandur626** [comment]
Cool thanks approving it.

**Review by chandur626 — APPROVED** [review]

**Review by SriPallaviDamuluri — APPROVED** [review]

**Review by 05sandesh — APPROVED** [review]
looks good

**Review by HariniBharata — APPROVED** [review]
Approved.

**Pull request merged**
